// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpeeJIYPYULa1Uia3Zg1yMmJvHiEYVyPA',
    appId: '1:769565171813:web:d164f5533bcf327dda268c',
    messagingSenderId: '769565171813',
    projectId: 'trip-genie-89de5',
    authDomain: 'trip-genie-89de5.firebaseapp.com',
    storageBucket: 'trip-genie-89de5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR8eTZYEteEn2U4pUW5svwbjzrYRftAdU',
    appId: '1:769565171813:android:9cab9e2179460028da268c',
    messagingSenderId: '769565171813',
    projectId: 'trip-genie-89de5',
    storageBucket: 'trip-genie-89de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJF3n9LEwqlM1AJrn36q-XxRkhyexKIao',
    appId: '1:769565171813:ios:16fdbd84e5b01f4fda268c',
    messagingSenderId: '769565171813',
    projectId: 'trip-genie-89de5',
    storageBucket: 'trip-genie-89de5.firebasestorage.app',
    iosBundleId: 'com.example.tripGenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJF3n9LEwqlM1AJrn36q-XxRkhyexKIao',
    appId: '1:769565171813:ios:16fdbd84e5b01f4fda268c',
    messagingSenderId: '769565171813',
    projectId: 'trip-genie-89de5',
    storageBucket: 'trip-genie-89de5.firebasestorage.app',
    iosBundleId: 'com.example.tripGenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpeeJIYPYULa1Uia3Zg1yMmJvHiEYVyPA',
    appId: '1:769565171813:web:cc28ceec94d867bada268c',
    messagingSenderId: '769565171813',
    projectId: 'trip-genie-89de5',
    authDomain: 'trip-genie-89de5.firebaseapp.com',
    storageBucket: 'trip-genie-89de5.firebasestorage.app',
  );
}
