// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:trip_genie/features/auth/data/models/user_model.dart';
import 'package:trip_genie/features/plan/data/models/trip_model.dart';
import 'package:trip_genie/features/travel_tips/data/models/travel_tip_model.dart';
import 'package:trip_genie/features/trip_info/data/models/places_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PlacesModelAdapter());
    registerAdapter(TravelTipModelAdapter());
    registerAdapter(TripModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PlacesModelAdapter());
    registerAdapter(TravelTipModelAdapter());
    registerAdapter(TripModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
